---
azs:
- name: z1
  cloud_properties: {availability_zone: (( grab terraform_outputs.zone0 )) }
- name: z2
  cloud_properties: {availability_zone: (( grab terraform_outputs.zone1 )) }
- name: z3
  cloud_properties: {availability_zone: (( grab terraform_outputs.zone2 )) }

compilation:
  vm_type: compilation
  az: z1
  network: cf
  reuse_compilation_vms: true
  workers: 6

vm_types:
- name: compilation
  cloud_properties:
    iam_instance_profile: compilation-vm
    instance_type: c3.large
    ephemeral_disk:
      size: 20480
      type: gp2
